<a href="https://colab.research.google.com/github/yhk775206/2023.RL2/blob/main/ex00.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("Hello World")

Hello World


#### 라이브러리(패키지) 로드

In [1]:
import numpy as np

In [2]:
def print_val(x):
  print("Type:", type(x))
  print("Shape:", x.shape)
  print("값:\n", x)
  print(" ")

In [3]:
x = np.array([1, 2, 3])
print_val(x)

x[0] = 5
print_val(x)

Type: <class 'numpy.ndarray'>
Shape: (3,)
값:
 [1 2 3]
 
Type: <class 'numpy.ndarray'>
Shape: (3,)
값:
 [5 2 3]
 


In [4]:
y = np.array([[1,2,3], [4,5,6]])
print_val(y)

Type: <class 'numpy.ndarray'>
Shape: (2, 3)
값:
 [[1 2 3]
 [4 5 6]]
 


In [6]:
a = np.zeros((2,2))
print_val(a)

Type: <class 'numpy.ndarray'>
Shape: (2, 2)
값:
 [[0. 0.]
 [0. 0.]]
 
